### ISSUE TITLE
Ethernet support for CAPL-like scripting

### ISSUE THREAD

**Issue by KhazAkar** [pragmaticlinuxblog/caplin#1]
Hi!
Is it possible to also use this project for communication with target over Ethernet? I've seen usage only for CANbus.
It's supported in Vector CAPL ;)

**Comment by pragmaticlinuxblog** [comment]
Hi,

The CAPLin framework was designed with CAN communication in mind. However, the framework is developed in the C language. This means that you can include and access all libraries on your Linux system. For Ethernet communication you an use the existing sockets functionality. Have a look at sys/socket.h.
